train:
  _target_: src.datasets.librispeech_kaggle.LibrispeechDatasetKaggleInp
  part: "train-clean-360"
  max_audio_length: null
  max_text_length: null
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.librispeech_kaggle.LibrispeechDatasetKaggleInp
  part: "test-clean"
  max_audio_length: null
  max_text_length: null
  instance_transforms: ${transforms.instance_transforms.inference}
