train:
  _target_: src.datasets.librispeech_kaggle.LibrispeechDatasetKaggle
  part: "train-clean-360"
  max_audio_length: null
  max_text_length: null
  limit: 64
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.librispeech_kaggle.LibrispeechDatasetKaggle
  part: test-clean"
  max_audio_length: null
  max_text_length: null
  limit: 64
  instance_transforms: ${transforms.instance_transforms.inference}
