train:
  _target_: src.datasets.librispeech_kaggle_inp.LibrispeechDatasetKaggleInp
  part: "train-clean-360"
  max_audio_length: 20.0
  max_text_length: 200
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.librispeech_kaggle_inp.LibrispeechDatasetKaggleInp
  part: "test-clean"
  max_audio_length: 20.0
  max_text_length: 200
  instance_transforms: ${transforms.instance_transforms.inference}
