train:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  max_audio_length: null
  max_text_length: null
  # limit: null
  instance_transforms: ${transforms.instance_transforms.train}
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  max_audio_length: null
  max_text_length: null
  limit: 10
  instance_transforms: ${transforms.instance_transforms.inference}
