train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.cer.BeamCERMetric
    name: "CER_(BeamSearch)"
    beam_size: 5
  - _target_: src.metrics.wer.BeamWERMetric
    name: "WER_(BeamSearch)"
    beam_size: 5
  - _target_: src.metrics.cer.LMCERMetric
    name: "CER_(LM_BeamSearch)"
    beam_size: 100
  - _target_: src.metrics.wer.LMWERMetric
    name: "WER_(LM_BeamSearch)"
    beam_size: 100