train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
      - _target_: src.transforms.wav_augs.PitchShift
        sample_rate: 16000
        min_transpose_semitones: -2
        max_transpose_semitones: 2
      - _target_: src.transforms.wav_augs.ColoredNoise
        sample_rate: 16000
        min_snr_in_db: 5
        max_snr_in_db: 15
      - _target_: src.transforms.wav_augs.Resample
        sample_rate: 16000
        speed_factor: 0.8
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
